### ISSUE TITLE
Wiki commands

### ISSUE THREAD

**Issue by ConnorAhern** [ConnorAhern/aspectfully#5]
**_We need to be able to have the bot search these wikis_**:
1. Wikipedia
2. Fandom

# Part 1: Getting a foundation
- [ ] Make a very barebones command to display info from MediaWiki wikis and remove the HTML from it (not converting to Markdown)
- [ ] Read the code & licensing of the Wiki-Bot repository

# Part 2: Markdown
- [ ] Copy over some basic Wiki-Bot code
- [ ] Remove HTML tags from the processed pages

**Comment by ConnorAhern** [comment]
Some progress in dd388de91b8d30c884aa634392f39b203e7479b3

**Comment by ConnorAhern** [comment]
#7 complete
